# Generated by Django 5.1.1 on 2024-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/ic%C3%B4ne-de-profil-avatar-par-d%C3%A9faut-m%C3%A9dias-sociaux-utilisateur-vectoriel-social-portrait-176194876.jpg'),
        ),
    ]
